version: "3.9"
services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./server
    container_name: mern-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env  
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    depends_on:
      - mongo

  frontend:
    build: ./client
    container_name: mern-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    user: root   # allows Jenkins to access docker.sock if needed
    ports:
      - "8080:8080"   # Jenkins UI
      - "50000:50000" # For Jenkins agent connections
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # let Jenkins control Docker
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false

volumes:
  mongo_data:
  jenkins_home:
