version: "3.9"
services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./server
    container_name: mern-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env  
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    depends_on:
      - mongo

  frontend:
    build: ./client
    container_name: mern-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo_data:
